### ISSUE TITLE
Protocol Translator #40

### ISSUE THREAD

**Issue by thelucyclub** [Driesboy/BigBrother-1.9.2#29]
What does this mean? I'm not sure and saw no other issues. Please explain.
`[Server thread/CRITICAL]: [BigBrother] Couldn't find a protocol translator for #40, disabling plugin`

**Comment by Driesboy** [comment]
genisys???

**Comment by thelucyclub** [comment]
ClearSky and I have tryed changing protocol to 40 and other things that might've fixed this, but none worked.

**Comment by Driesboy** [comment]
clearsky php5???

**Comment by Driesboy** [comment]
i have only updated php7 sorry :(

**Comment by thelucyclub** [comment]
ClearSky PHP7

**Comment by matthew4444** [comment]
kk,cant wait to build th phar and make myn server finally work on my brothes pc

**Comment by Driesboy** [comment]
HAHA

**Comment by matthew4444** [comment]
what hhaha?

**Comment by Driesboy** [comment]
i have created new branch for Clearsky php7

**Comment by matthew4444** [comment]
CAN I SEE

**Comment by Driesboy** [comment]
fixed

**Comment by matthew4444** [comment]
CAN U ADD CLEARSKY PHP7 PHAR?

**Comment by Driesboy** [comment]
soon i will add jenkins system for this plugin

**Comment by matthew4444** [comment]
can u work on the pets plugin in the repo u have in the meantime??

**Comment by Driesboy** [comment]
i am working on the pets plugin from LostTeam

**Comment by matthew4444** [comment]
well can u finish it now,or mnake pets follow players in  that repo

**Comment by thelucyclub** [comment]
... I am also working on pets. Thank you for the new branch. Hope it works!

**Comment by matthew4444** [comment]
Thx

**Comment by thelucyclub** [comment]
Ignore @matthew4444 he is pest who follows me everywhere. idk even know why. he is so demanding and i tell him if he wants things, learn php.

**Comment by matthew4444** [comment]
i work on many plugin dev teams with him,and since everything weve been through thatas very offsensive
